# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscellaneous', '0001_initial'),
        ('participant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombDisposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name")),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('certificate', models.BooleanField(default=False, verbose_name='Given certificate')),
                ('verification', models.BooleanField(default=False, verbose_name='Verified')),
                ('round_one', models.IntegerField(blank=True, null=True, verbose_name='Round One Score')),
                ('qualify_round_one', models.BooleanField(default=False, verbose_name='Qualified for Round Two')),
                ('round_two', models.IntegerField(blank=True, null=True, verbose_name='Round Two Score')),
                ('qualify_round_two', models.BooleanField(default=False, verbose_name='Qualified for Round Three')),
                ('round_three', models.IntegerField(blank=True, null=True, verbose_name='Round Three Score')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.Country')),
                ('participant', models.ManyToManyField(help_text="<strong>Type in team member's name, mobile or e-mail to begin a search</strong><br>", related_name='team_bombdisposal_related', to='participant.Participant', verbose_name='Team Members')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.State')),
            ],
            options={
                'verbose_name': 'BombDisposal',
                'verbose_name_plural': 'BombDisposal',
            },
        ),
        migrations.CreateModel(
            name='Bricks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name")),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('certificate', models.BooleanField(default=False, verbose_name='Given certificate')),
                ('verification', models.BooleanField(default=False, verbose_name='Verified')),
                ('round_one', models.IntegerField(blank=True, null=True, verbose_name='Round One Score')),
                ('qualify_round_one', models.BooleanField(default=False, verbose_name='Qualified for Round Two')),
                ('round_two', models.IntegerField(blank=True, null=True, verbose_name='Round Two Score')),
                ('qualify_round_two', models.BooleanField(default=False, verbose_name='Qualified for Round Three')),
                ('round_three', models.IntegerField(blank=True, null=True, verbose_name='Round Three Score')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.Country')),
                ('participant', models.ManyToManyField(help_text="<strong>Type in team member's name, mobile or e-mail to begin a search</strong><br>", related_name='team_bricks_related', to='participant.Participant', verbose_name='Team Members')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.State')),
            ],
            options={
                'verbose_name': 'B.R.I.C.K.S',
                'verbose_name_plural': 'B.R.I.C.K.S',
            },
        ),
        migrations.CreateModel(
            name='Conquest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name")),
                ('street', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('certificate', models.BooleanField(default=False, verbose_name='Given certificate')),
                ('verification', models.BooleanField(default=False, verbose_name='Verified')),
                ('round_one', models.IntegerField(blank=True, null=True, verbose_name='Round One Score')),
                ('qualify_round_one', models.BooleanField(default=False, verbose_name='Qualified for Round Two')),
                ('round_two', models.IntegerField(blank=True, null=True, verbose_name='Round Two Score')),
                ('qualify_round_two', models.BooleanField(default=False, verbose_name='Qualified for Round Three')),
                ('round_three', models.IntegerField(blank=True, null=True, verbose_name='Round Three Score')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.Country')),
                ('participant', models.ManyToManyField(help_text="<strong>Type in team member's name, mobile or e-mail to begin a search</strong><br>", related_name='team_conquest_related', to='participant.Participant', verbose_name='Team Members')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.State')),
            ],
            options={
                'verbose_name': 'Conquest',
                'verbose_name_plural': 'Conquest',
            },
        ),
    ]
