# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droidblitz',
            options={'verbose_name': 'Droid Blitz Team'},
        ),
        migrations.AlterModelOptions(
            name='sheldon',
            options={'verbose_name': 'S.H.E.L.D.O.N. Team'},
        ),
        migrations.AlterModelOptions(
            name='sherlock',
            options={'verbose_name': 'Sherlock Team'},
        ),
        migrations.AlterModelOptions(
            name='summit',
            options={'verbose_name': 'Summit Team'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouse Team'},
        ),
        migrations.AddField(
            model_name='droidblitz',
            name='name',
            field=models.CharField(default='Not provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheldon',
            name='name',
            field=models.CharField(default='Not provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sherlock',
            name='name',
            field=models.CharField(default='Not provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summit',
            name='name',
            field=models.CharField(default='Not provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Not provided', max_length=50),
            preserve_default=False,
        ),
    ]
