# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160121_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droidblitz',
            name='name',
            field=models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name"),
        ),
        migrations.AlterField(
            model_name='sheldon',
            name='name',
            field=models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name"),
        ),
        migrations.AlterField(
            model_name='sherlock',
            name='name',
            field=models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name"),
        ),
        migrations.AlterField(
            model_name='summit',
            name='name',
            field=models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name"),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text="Provide Team leader's or caretaker's full name", max_length=50, verbose_name="Receiver's Name"),
        ),
    ]
