# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscellaneous', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail address')),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], verbose_name='Year of study')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.College')),
            ],
        ),
    ]
