# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20160121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='college',
            field=models.ForeignKey(help_text='Select others if you cannot find your college', on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.College'),
        ),
    ]
