from django.contrib import admin
from rbtxportal.eventmanager.models import *

admin.site.register(Team)
admin.site.register(Import)
admin.site.register(LumosFirstRound)
admin.site.register(LumosSecondRound)
admin.site.register(LumosThirdRound)
admin.site.register(OverhaulFirstRound)
admin.site.register(OverhaulSecondRound)
admin.site.register(OverhaulThirdRound)
admin.site.register(AbyssFirstRound)
admin.site.register(AbyssSecondRound)
admin.site.register(AbyssThirdRound)
admin.site.register(ACROSSFirstRound)
admin.site.register(ACROSSSecondRound)
admin.site.register(ACROSSThirdRound)
admin.site.register(SeekerFirstRound)
admin.site.register(SeekerSecondRound)
admin.site.register(SeekerThirdRound)
